swap double quotes for single quotes

diff --git a/scripts/dpotp b/scripts/dpotp
--- a/scripts/dpotp
+++ b/scripts/dpotp
@@ -3,19 +3,19 @@
 shopt -s nullglob globstar
 
 typeit=0
-if [[ $1 == "--type" ]]; then
+if [[ $1 == '--type' ]]; then
 	typeit=1
 	shift
 fi
 
 if [[ -n $WAYLAND_DISPLAY ]]; then
-	dmenu=dmenu-wl
-	xdotool="ydotool type --file -"
+	dmenu='dmenu-wl'
+	xdotool='ydotool type --file -'
 elif [[ -n $DISPLAY ]]; then
-	dmenu=dmenu
-	xdotool="xdotool type --clearmodifiers --file -"
+	dmenu='dmenu'
+	xdotool='xdotool type --clearmodifiers --file -'
 else
-	echo "Error: No Wayland or X11 display detected" >&2
+	echo 'Error: No Wayland or X11 display detected' >&2
 	exit 1
 fi
 
